# Generated by Django 6.0 on 2025-12-29 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('species', models.CharField(choices=[('CATTLE', 'Cattle'), ('CHICKEN', 'Chicken'), ('GOAT', 'Goat'), ('SHEEP', 'Sheep'), ('OTHER', 'Other')], default='CATTLE', max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('DECEASED', 'Deceased'), ('SICK', 'Sick')], default='ACTIVE', max_length=20)),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=6, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='livestock/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to='core.farm')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalHealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('vet_name', models.CharField(blank=True, max_length=100)),
                ('condition_notes', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('medication', models.CharField(blank=True, max_length=255)),
                ('next_vaccination_date', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight at time of record', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='livestock.livestock')),
            ],
        ),
    ]
