# Generated by Django 6.0 on 2025-12-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='category',
            field=models.CharField(choices=[('HEIFER', 'Heifer'), ('CALF', 'Calf'), ('BULL', 'Bull'), ('COW', 'Cow'), ('BUCK', 'Buck'), ('DOE', 'Doe'), ('KID', 'Kid'), ('RAM', 'Ram'), ('EWE', 'Ewe'), ('LAMB', 'Lamb'), ('LAYER', 'Layer'), ('BROILER', 'Broiler'), ('KIENYEJI', 'Kienyeji'), ('CHICK', 'Chick'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='livestock',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='livestock',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of animals (useful for poultry)'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='species',
            field=models.CharField(choices=[('CATTLE', 'Cattle'), ('POULTRY', 'Poultry'), ('GOAT', 'Goat'), ('SHEEP', 'Sheep'), ('OTHER', 'Other')], default='CATTLE', max_length=20),
        ),
    ]
