# Generated by Django 6.0.5 on 2026-05-24 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_farm_boundary_polygon_farm_description_farm_email_and_more'),
        ('livestock', '0002_livestock_category_livestock_custom_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalhealthrecord',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='animalhealthrecord',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='livestock/health/'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='species',
            field=models.CharField(choices=[('CATTLE', 'Cattle'), ('POULTRY', 'Poultry'), ('GOAT', 'Goat'), ('SHEEP', 'Sheep'), ('PIG', 'Pig'), ('RABBIT', 'Rabbit'), ('OTHER', 'Other')], default='CATTLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('DECEASED', 'Deceased'), ('SICK', 'Sick'), ('PREGNANT', 'Pregnant'), ('QUARANTINE', 'Quarantine')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='tag_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='livestock',
            unique_together={('farm', 'tag_id')},
        ),
        migrations.CreateModel(
            name='AnimalGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='Pen, paddock, or section name', max_length=100)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='livestock/groups/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_groups', to='core.farm')),
            ],
        ),
        migrations.AddField(
            model_name='livestock',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='livestock.animalgroup'),
        ),
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sire_external', models.CharField(blank=True, help_text='External sire info if not in system', max_length=100)),
                ('mating_date', models.DateField()),
                ('expected_due_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('MATED', 'Mated'), ('CONFIRMED_PREGNANT', 'Confirmed Pregnant'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PLANNED', max_length=20)),
                ('offspring_count', models.PositiveIntegerField(default=0)),
                ('offspring_details', models.TextField(blank=True)),
                ('method', models.CharField(blank=True, help_text='Natural, AI, etc.', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_as_dam', to='livestock.livestock')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to='core.farm')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeding_as_sire', to='livestock.livestock')),
            ],
            options={
                'ordering': ['-mating_date'],
            },
        ),
        migrations.CreateModel(
            name='FeedingProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('feed_type', models.CharField(choices=[('HAY', 'Hay'), ('SILAGE', 'Silage'), ('CONCENTRATES', 'Concentrates'), ('DAIRY_MEAL', 'Dairy Meal'), ('MINERALS', 'Minerals'), ('NAPIER', 'Napier Grass'), ('MAIZE_STALKS', 'Maize Stalks'), ('LAYERS_MASH', 'Layers Mash'), ('CHICK_MASH', 'Chick Mash'), ('GROWERS_MASH', 'Growers Mash'), ('OTHER', 'Other')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_programs', to='core.farm')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedings', to='livestock.animalgroup')),
                ('livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedings', to='livestock.livestock')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MortalityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('cause', models.CharField(choices=[('DISEASE', 'Disease'), ('ACCIDENT', 'Accident'), ('OLD_AGE', 'Old Age'), ('PREDATOR', 'Predator Attack'), ('BIRTH_COMPLICATION', 'Birth Complication'), ('POISONING', 'Poisoning'), ('UNKNOWN', 'Unknown'), ('OTHER', 'Other')], default='UNKNOWN', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('vet_report', models.TextField(blank=True)),
                ('financial_loss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='livestock/mortality/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to='livestock.livestock')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('disease', models.CharField(blank=True, max_length=100)),
                ('scheduled_date', models.DateField()),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('SKIPPED', 'Skipped')], default='SCHEDULED', max_length=15)),
                ('dosage', models.CharField(blank=True, max_length=50)),
                ('vet_name', models.CharField(blank=True, max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_booster_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedules', to='core.farm')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to='livestock.animalgroup')),
                ('livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='livestock.livestock')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
    ]
