# Generated by Django 6.0 on 2025-12-29 22:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('livestock', '0002_livestock_category_livestock_custom_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('produce_type', models.CharField(choices=[('MILK', 'Milk'), ('EGGS', 'Eggs'), ('MAIZE', 'Maize'), ('OTHER', 'Other')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Total quantity (e.g. liters, count, bags)', max_digits=10)),
                ('unit', models.CharField(default='units', max_length=20)),
                ('morning_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Morning milk in liters', max_digits=10, null=True)),
                ('noon_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Noon milk in liters', max_digits=10, null=True)),
                ('evening_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Evening milk in liters', max_digits=10, null=True)),
                ('crates', models.DecimalField(blank=True, decimal_places=1, help_text='Calculated crates (1 crate = 30 eggs)', max_digits=10, null=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_records', to='core.farm')),
                ('livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produce_records', to='livestock.livestock')),
            ],
        ),
    ]
