# Generated by Django 6.0 on 2025-12-29 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('product', models.CharField(choices=[('EGGS', 'Eggs'), ('MILK', 'Milk'), ('TOMATOES', 'Tomatoes'), ('MANURE', 'Manure'), ('OTHER', 'Other')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(help_text='e.g. cartons, liters, crates', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('PENDING', 'Pending')], default='PAID', max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('supplier', models.CharField(max_length=255)),
                ('items', models.JSONField(default=dict, help_text='Line items of purchase')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.farm')),
            ],
        ),
    ]
