# Generated by Django 6.0 on 2025-12-29 22:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_initial'),
        ('core', '0001_initial'),
        ('livestock', '0002_livestock_category_livestock_custom_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sale',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sale',
            name='livestock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='livestock.livestock'),
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('FEED', 'Feed'), ('LABOR', 'Labor'), ('FUEL', 'Fuel'), ('MAINTENANCE', 'Maintenance'), ('TREATMENT', 'Treatment'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='core.farm')),
                ('related_livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures', to='livestock.livestock')),
            ],
        ),
    ]
