# Generated by Django 6.0 on 2025-12-29 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='worker',
            name='employment_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('CASUAL', 'Casual')], default='PERMANENT', max_length=20),
        ),
        migrations.CreateModel(
            name='Kibarua',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_name', models.CharField(blank=True, help_text='For unregistered casual workers', max_length=255)),
                ('date', models.DateField()),
                ('work_description', models.TextField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kibarua_records', to='core.farm')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kibarua_records', to='workforce.worker')),
            ],
        ),
    ]
