# Generated by Django 6.0.5 on 2026-05-24 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_farm_boundary_polygon_farm_description_farm_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_type', models.CharField(choices=[('MAIZE', 'Maize'), ('BEANS', 'Beans'), ('WHEAT', 'Wheat'), ('RICE', 'Rice'), ('POTATOES', 'Potatoes'), ('TOMATOES', 'Tomatoes'), ('CABBAGE', 'Cabbage'), ('KALE', 'Kale'), ('ONIONS', 'Onions'), ('CARROTS', 'Carrots'), ('TEA', 'Tea'), ('COFFEE', 'Coffee'), ('SUGARCANE', 'Sugarcane'), ('NAPIER', 'Napier Grass'), ('SUNFLOWER', 'Sunflower'), ('SORGHUM', 'Sorghum'), ('MILLET', 'Millet'), ('BANANAS', 'Bananas'), ('AVOCADO', 'Avocado'), ('MACADAMIA', 'Macadamia'), ('OTHER', 'Other')], max_length=30)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('PLANTED', 'Planted'), ('GROWING', 'Growing'), ('FLOWERING', 'Flowering'), ('HARVESTING', 'Harvesting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PLANNING', max_length=20)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('seed_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seed_unit', models.CharField(blank=True, max_length=20)),
                ('expected_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yield_unit', models.CharField(default='kg', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crops/seasons/')),
                ('notes', models.TextField(blank=True)),
                ('custom_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_seasons', to='core.farm')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_seasons', to='core.farmplot')),
            ],
            options={
                'ordering': ['-planting_date'],
            },
        ),
        migrations.CreateModel(
            name='CropActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('PLOUGHING', 'Ploughing'), ('PLANTING', 'Planting'), ('WEEDING', 'Weeding'), ('FERTILIZING', 'Fertilizing'), ('SPRAYING', 'Spraying'), ('IRRIGATING', 'Irrigating'), ('PRUNING', 'Pruning'), ('THINNING', 'Thinning'), ('MULCHING', 'Mulching'), ('HARVESTING', 'Harvesting'), ('OTHER', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('inputs_used', models.CharField(blank=True, help_text='e.g. DAP 50kg, CAN 25kg', max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labor_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('workers_count', models.PositiveIntegerField(default=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crops/activities/')),
                ('custom_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crops.cropseason')),
            ],
            options={
                'verbose_name_plural': 'Crop activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('quality_grade', models.CharField(blank=True, max_length=20)),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('workers_count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crops/harvests/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='crops.cropseason')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PestDisease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PEST', 'Pest'), ('DISEASE', 'Disease'), ('WEED', 'Weed')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('date_detected', models.DateField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('SEVERE', 'Severe')], default='LOW', max_length=10)),
                ('affected_area_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('treatment', models.TextField(blank=True)),
                ('treatment_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crops/pests/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_diseases', to='crops.cropseason')),
            ],
            options={
                'verbose_name_plural': 'Pests & diseases',
                'ordering': ['-date_detected'],
            },
        ),
    ]
