# Generated by Django 6.0.5 on 2026-05-24 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='boundary_polygon',
            field=models.JSONField(blank=True, help_text='GeoJSON polygon coordinates for farm boundary', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='farms/logos/'),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='farm',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='farms/photos/'),
        ),
        migrations.AddField(
            model_name='farm',
            name='total_acreage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.CreateModel(
            name='FarmPlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size_acres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('boundary_polygon', models.JSONField(blank=True, help_text='GeoJSON polygon coordinates for plot boundary', null=True)),
                ('soil_type', models.CharField(choices=[('CLAY', 'Clay'), ('SANDY', 'Sandy'), ('LOAM', 'Loam'), ('SILT', 'Silt'), ('PEAT', 'Peat'), ('CHALK', 'Chalk'), ('RED', 'Red Soil'), ('BLACK_COTTON', 'Black Cotton'), ('OTHER', 'Other')], default='LOAM', max_length=20)),
                ('irrigation_type', models.CharField(blank=True, max_length=50)),
                ('current_crop', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / In Use'), ('FALLOW', 'Fallow'), ('PREPARING', 'Being Prepared'), ('HARVESTED', 'Harvested'), ('IDLE', 'Idle')], default='IDLE', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='plots/photos/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='core.farm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
