# Generated by Django 6.0.5 on 2026-05-24 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_farm_boundary_polygon_farm_description_farm_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('hero_card_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('about_chip_1', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('about_chip_2', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('about_main', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('feature_1', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('feature_2', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('feature_3', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('sustain_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('advance_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('crop_coffee', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('crop_maize', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('crop_vegetables', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('crop_avocado', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('animal_cow', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('animal_poultry', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('animal_goat', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('animal_sheep', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Content',
                'verbose_name_plural': 'Landing Page Content',
            },
        ),
    ]
