# Generated by Django 6.0.5 on 2026-05-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_landingcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='color_accent',
            field=models.CharField(blank=True, default='#84CC16', max_length=9),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='color_danger',
            field=models.CharField(blank=True, default='#DC2626', max_length=9),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='color_landing_cream',
            field=models.CharField(blank=True, default='#FAFAF7', max_length=9),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='color_landing_dark',
            field=models.CharField(blank=True, default='#0B1410', max_length=9),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='color_landing_green',
            field=models.CharField(blank=True, default='#84CC16', max_length=9),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='color_landing_green_deep',
            field=models.CharField(blank=True, default='#4D7C0F', max_length=9),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='color_primary',
            field=models.CharField(blank=True, default='#4D7C0F', max_length=9),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='color_primary_hover',
            field=models.CharField(blank=True, default='#3F6212', max_length=9),
        ),
    ]
